version: 2.1
orbs:
  aws-ecr: circleci/aws-ecr@4.0.1
  aws-ecs: circleci/aws-ecs@0.0.8

workflows:
  build-and-deploy:
    jobs:
      - aws-ecr/build_and_push_image:
          context: aws-global
          account-url: AWS_ECR_ACCOUNT_URL
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          create-repo: true
          dockerfile: Dockerfile
          repo: instaclustr-metrics-forwarder
          tag: "${CIRCLE_SHA1}"
          filters:
            branches:
              only: master

      - aws-ecs/deploy-service-update:
          name: deploy-staging
          requires:
            - aws-ecr/build_and_push_image
          cluster-name: "${AWS_RESOURCE_NAME_PREFIX}"
          family: "${AWS_RESOURCE_NAME_PREFIX}-staging"

      - promote-to-production:
          type: approval
          requires:
            - deploy-staging

      - aws-ecs/deploy-service-update:
          name: deploy-production
          requires:
            - promote-to-production
          cluster-name: "${AWS_RESOURCE_NAME_PREFIX}"
          family: "${AWS_RESOURCE_NAME_PREFIX}-production"
