version: 2.1
orbs:
  aws-ecr: circleci/aws-ecr@4.0.1

workflows:
  build-and-publish:
    jobs:
      - aws-ecr/build_and_push_image:
          context: aws-global
          account-url: AWS_ECR_ACCOUNT_URL
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          create-repo: true
          dockerfile: Dockerfile
          repo: instaclustr-metrics-forwarder
          filters:
            branches:
              only: master
